version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
  
  php:
    image: php:8.1-fpm
    working_dir: /var/www/php #thu muc trong docker luu tru code
    volumes:
      - ./src:/var/www/php #anh xa thu muc local toi thu muc container
    depends_on:
      - mysql
  
  mysql:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
      MYSQL_DATABASE: example_database
      MYSQL_USER: newuser
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD:?err}
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:        
